# Generated by Django 5.0.14 on 2026-07-30 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_plan_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='category',
            field=models.CharField(choices=[('app_review', 'App Reviews'), ('movie_review', 'Movie Reviews'), ('chat', 'Chat with Foreigners')], max_length=20),
        ),
    ]
