# Generated by Django 5.0.14 on 2026-08-06 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activation', '0002_remove_paymentgateway_recipient_name_and_more'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositrequest',
            name='gateway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_requests', to='activation.paymentgateway'),
        ),
        migrations.AddField(
            model_name='depositrequest',
            name='gateway_display_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='depositrequest',
            name='gateway_group',
            field=models.CharField(blank=True, choices=[('kenya', 'Kenya'), ('uganda_tanzania', 'Uganda / Tanzania'), ('ghana_nigeria', 'Ghana / Nigeria (Eversend)'), ('other', 'Other countries')], max_length=20),
        ),
    ]
