# Generated by Django 5.0.14 on 2026-08-06 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentgateway',
            name='recipient_name',
        ),
        migrations.RemoveField(
            model_name='paymentgateway',
            name='paybill_number',
        ),
        migrations.RemoveField(
            model_name='paymentgateway',
            name='till_number',
        ),
        migrations.RemoveField(
            model_name='paymentgateway',
            name='account_reference',
        ),
        migrations.RemoveField(
            model_name='paymentgateway',
            name='is_automatic',
        ),
        migrations.RemoveField(
            model_name='paymentgateway',
            name='recipient_phone',
        ),
        migrations.RemoveField(
            model_name='activationsubmission',
            name='method_type',
        ),
        migrations.RemoveField(
            model_name='paymentgateway',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='paymentgateway',
            name='method_type',
        ),
        migrations.AddField(
            model_name='activationsubmission',
            name='gateway_display_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='activationsubmission',
            name='gateway_group',
            field=models.CharField(blank=True, choices=[('kenya', 'Kenya'), ('uganda_tanzania', 'Uganda / Tanzania'), ('ghana_nigeria', 'Ghana / Nigeria (Eversend)'), ('other', 'Other countries')], max_length=20),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='description',
            field=models.TextField(default='', help_text='The full payment guide shown to the user — on BOTH the activation page and the deposit page. One field, one source of truth: edit it here and both pages update together, so they can never drift out of sync.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='group',
            field=models.CharField(choices=[('kenya', 'Kenya'), ('uganda_tanzania', 'Uganda / Tanzania'), ('ghana_nigeria', 'Ghana / Nigeria (Eversend)'), ('other', 'Other countries')], default=' ', editable=False, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activationsubmission',
            name='gateway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activation_submissions_set', to='activation.paymentgateway'),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='display_name',
            field=models.CharField(help_text="Shown as the option label, e.g. 'Pay via M-Pesa Till (Instant)'.", max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Off = hidden from users entirely. A country with zero active rows shows a 'Coming soon' message on the frontend."),
        ),
        migrations.CreateModel(
            name='GhanaNigeriaPaymentGateway',
            fields=[
                ('paymentgateway_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activation.paymentgateway')),
                ('eversend_link', models.URLField(help_text='Your Eversend payment link, e.g. https://eversend.me/pay/yourhandle')),
                ('recipient_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Ghana/Nigeria payment method (Eversend)',
                'verbose_name_plural': 'Ghana/Nigeria payment methods (Eversend)',
            },
            bases=('activation.paymentgateway',),
        ),
        migrations.CreateModel(
            name='KenyaPaymentGateway',
            fields=[
                ('paymentgateway_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activation.paymentgateway')),
                ('is_automatic', models.BooleanField(default=False, help_text='On = Daraja STK push (instant, no proof needed). Off = manual till, admin-approved after the user submits proof.')),
                ('till_number', models.CharField(blank=True, max_length=20)),
                ('paybill_number', models.CharField(blank=True, max_length=20)),
                ('account_reference', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Kenya payment method',
                'verbose_name_plural': 'Kenya payment methods',
            },
            bases=('activation.paymentgateway',),
        ),
        migrations.CreateModel(
            name='OtherPaymentGateway',
            fields=[
                ('paymentgateway_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activation.paymentgateway')),
                ('recipient_name', models.CharField(max_length=100)),
                ('recipient_phone', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Other country payment method',
                'verbose_name_plural': 'Other country payment methods',
            },
            bases=('activation.paymentgateway',),
        ),
        migrations.CreateModel(
            name='UgandaTanzaniaPaymentGateway',
            fields=[
                ('paymentgateway_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activation.paymentgateway')),
                ('recipient_name', models.CharField(max_length=100)),
                ('recipient_phone', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Uganda/Tanzania payment method',
                'verbose_name_plural': 'Uganda/Tanzania payment methods',
            },
            bases=('activation.paymentgateway',),
        ),
    ]
