# Generated by hand to match Django's autogenerated migration style
# (adds Country.activation_fee, User.is_activated, User.activated_at)

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_country_exchange_rate_to_kes_user_referral_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='activation_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
