# Generated by Django 5.0.14 on 2026-07-31 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applisting',
            name='package_name',
            field=models.CharField(blank=True, help_text='Google Play package id (e.g. com.example.app) — set only for scraped entries', max_length=255, null=True, unique=True),
        ),
    ]
