# Generated by Django 5.0.14 on 2026-07-23 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='chat_profiles/')),
                ('bio', models.TextField(blank=True)),
                ('payout_amount_usd', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rate_per_message_kes', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['payout_amount_usd'],
            },
        ),
    ]
