# Generated by Django 5.0.14 on 2026-07-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit_manual', 'Manual deposit (admin-approved)'), ('deposit_automatic', 'Automatic deposit (Daraja)'), ('withdrawal', 'Withdrawal'), ('chat_earning', 'Chat earning'), ('survey_earning', 'Survey earning'), ('wheel_earning', 'Wheel spin earning'), ('app_review_earning', 'App review earning'), ('movie_review_earning', 'Movie review earning'), ('referral_commission', 'Referral commission'), ('plan_purchase', 'Plan purchase'), ('refund', 'Refund'), ('admin_adjustment', 'Admin adjustment')], max_length=25),
        ),
    ]
