# Generated by Django 5.0.14 on 2026-07-30 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('options', models.JSONField(help_text='List of answer strings, e.g. ["Nairobi", "Mombasa", "Kisumu", "Eldoret"]')),
                ('correct_option', models.PositiveSmallIntegerField(help_text="0-based index into 'options' for the correct answer")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('question_ids', models.JSONField(help_text='The 10 SurveyQuestion ids presented, in the order shown')),
                ('answers', models.JSONField(blank=True, help_text="User's submitted 0-based answer indices, same order as question_ids", null=True)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('credited_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency_code', models.CharField(blank=True, max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
