# Generated by Django 5.0.14 on 2026-07-30 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatprofile',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatprofile',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
