# Generated by Django 5.0.14 on 2026-10-02 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('promo', 'Promotion'), ('system', 'System')], default='promo', max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, help_text='Optional in-app route, e.g. /loans', max_length=300)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional. Hidden from users after this time.', null=True)),
                ('sent_count', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('refund', 'Refund'), ('survey', 'Survey earning'), ('movie_review', 'Movie review earning'), ('app_review', 'App review earning'), ('wheel', 'Wheel spin'), ('chat', 'Chat earning'), ('referral', 'Referral commission'), ('loan', 'Loan'), ('plan', 'Plan'), ('system', 'System'), ('promo', 'Promotion')], default='system', max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('message', models.TextField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency_code', models.CharField(blank=True, max_length=5)),
                ('link', models.CharField(blank=True, max_length=300)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional. Hidden from the user after this time.', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx'), models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx')],
            },
        ),
    ]
